spring.application.name=restdemo

spring.datasource.url=jdbc:postgresql://localhost:5432/coffee
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

greeting.name=Dakota
greeting.coffee=${greeting.name} is drinking Cafe Cereza

droid.description=Small, rolling android. Probably doesn't drink coffee.
droid.id=BB-8