spring.application.name=restdemo
spring.datasource.url=jdbc:postgresql://localhost:5432/coffee
spring.datasource.username=pg-user
spring.datasource.password=qwertyvbnm
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect